version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 100
  ignore:
  - dependency-name: NUnit
    versions:
    - 3.13.0
    - 3.13.1
  - dependency-name: Google.Protobuf
    versions:
    - 3.15.0
    - 3.15.1
    - 3.15.4
  - dependency-name: FsCheck.Xunit
    versions:
    - 2.14.5
    - 2.15.0
  - dependency-name: FsCheck
    versions:
    - 2.14.5
  - dependency-name: FluentAssertions
    versions:
    - 5.9.0
